### ISSUE TITLE
Test example

### ISSUE THREAD

**Issue by gunerhui** [PhotoRoom/fast-foreground-estimation#1]
how to test the result?
can you give an example?

**Comment by 1goodone** [comment]
> how to test the result? can you give an example?
Did you figure out how to use it, and when I used it, it was all black

**Comment by thenajjar** [comment]
image_path = './image1.jpg'
image = cv2.imread(image_path)
alpha = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
output = FB_blur_fusion_foreground_estimator_2(image, alpha)
cv2.imshow('Contours', output)

**Comment by iamtekeste** [comment]
@thenajjar I gave that a shot and saved the contents of output like so
`cv2.imwrite("awesome.jpg", output)` and all I am seeing is all black image just like @1goodone 

Would love any help I can get.

**Comment by MarcoForte** [comment]
Hello @iamtekeste , I just uploaded a jupyter notebook which gives an example usage. 

If the image output is all black from `cv2.imwrite("awesome.jpg", output)`, it is commonly from `output` not being correctly scaled to between `0-255`.
